name: is_takip_sistemi
description: İş Takip Sistemi

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^2.24.2
  firebase_auth: ^4.15.3
  cloud_firestore: ^4.13.6
  provider: ^6.1.1
  shared_preferences: ^2.2.2
  intl: ^0.18.1
  fl_chart: ^0.65.0
  file_picker: ^6.1.1
  timeago: ^3.5.0
  share_plus: ^7.2.1
  path_provider: ^2.1.2
  flutter_typeahead: ^4.7.0
  firebase_storage: ^11.5.6
  firebase_messaging: ^14.7.10
  http: ^1.1.2
  image_picker: ^1.0.7
  url_launcher: ^6.2.2
  emoji_picker_flutter: ^1.6.3
  record: ^5.0.4
  permission_handler: ^11.1.0
  path: ^1.8.3
  photo_view: ^0.14.0
  uuid: ^4.2.2
  flutter_speed_dial: ^7.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/
