name: is_takip_sistemi
description: İş takip sistemi mobil uygulaması.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  http: ^1.1.0
  provider: ^6.0.5
  shared_preferences: ^2.2.0
  socket_io_client: ^2.0.2
  flutter_local_notifications: ^15.1.0+1
  intl: ^0.18.1
  file_picker: ^5.5.0
  path_provider: ^2.1.1
  image_picker: ^1.0.4
  url_launcher: ^6.1.12
  flutter_markdown: ^0.6.17
  cached_network_image: ^3.2.3
  open_file: ^3.3.2
  mime: ^1.0.4
  path: ^1.8.3
  fixnum: ^1.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.2

flutter:
  uses-material-design: true
  
  assets:
    - assets/images/
    - assets/icons/

  fonts:
    - family: Roboto
      fonts:
        - asset: assets/fonts/Roboto-Regular.ttf
        - asset: assets/fonts/Roboto-Medium.ttf
          weight: 500
        - asset: assets/fonts/Roboto-Bold.ttf
          weight: 700
