// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBBLlWPPnFxuJfxpb0j9XHwPjmQgTvYs8Q',
    appId: '1:795393167329:web:0485b04c707e0c00ca4ca0',
    messagingSenderId: '795393167329',
    projectId: 'is-takip-sistemi-69ca5',
    authDomain: 'is-takip-sistemi-69ca5.firebaseapp.com',
    storageBucket: 'is-takip-sistemi-69ca5.firebasestorage.app',
    measurementId: 'G-WD0QL34Z9M',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDiaALmm-KD5LTzoZcwZimM3b3SJ5KeEx8',
    appId: '1:795393167329:android:d1eacfa19e3d38d8ca4ca0',
    messagingSenderId: '795393167329',
    projectId: 'is-takip-sistemi-69ca5',
    storageBucket: 'is-takip-sistemi-69ca5.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAjsuyzI6n17s8n3p-hGD6e1Q7kW0q3DQM',
    appId: '1:795393167329:ios:28cef0e6760a89d4ca4ca0',
    messagingSenderId: '795393167329',
    projectId: 'is-takip-sistemi-69ca5',
    storageBucket: 'is-takip-sistemi-69ca5.firebasestorage.app',
    iosBundleId: 'com.example.isTakipSistemi',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAjsuyzI6n17s8n3p-hGD6e1Q7kW0q3DQM',
    appId: '1:795393167329:ios:28cef0e6760a89d4ca4ca0',
    messagingSenderId: '795393167329',
    projectId: 'is-takip-sistemi-69ca5',
    storageBucket: 'is-takip-sistemi-69ca5.firebasestorage.app',
    iosBundleId: 'com.example.isTakipSistemi',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBBLlWPPnFxuJfxpb0j9XHwPjmQgTvYs8Q',
    appId: '1:795393167329:web:f64e475aba934a3eca4ca0',
    messagingSenderId: '795393167329',
    projectId: 'is-takip-sistemi-69ca5',
    authDomain: 'is-takip-sistemi-69ca5.firebaseapp.com',
    storageBucket: 'is-takip-sistemi-69ca5.firebasestorage.app',
    measurementId: 'G-ECC2MRJHG4',
  );

}